# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2-rc-2
loader_version=0.19.3

# Mod Properties
mod_version=1.2.4
maven_group=us.potatoboy
archives_base_name=htm

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.1+26.2
translation_version=3.1.0+26.2
protection_api_version=2.0.0
file_fix_utils_version=0.1.3-26.1
